# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eOgaEBdEfVfzwwnZm02PcUbFm2r8XfoZ
"""

import pickle
import streamlit as st

import os
os.listdir()

model= pickle.load(open('spam123.pkl','rb'))
cv= pickle.load(open('vect123.pkl','rb'))

def main():
  st.title("Email Spam Classification Application")
  st.write("This is an Machine Learning Application to classify the mails/messages")
  st.subheader("Classification")
  user_input=st.text_area("Enter an email to classify", height=100)
  if st.button("Classify"):
    data=[user_input]
    print(data)
    vec=cv.transform(data).toarray()
    result=model.predict(vec)
    if result[0]==0:
      st.success("This is not a Spam Email")
    else :
      st.error("This is a Spam Email")

main()
